//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2009.11.26 дк 04:48:36 CST 
//


package com.onceas.descriptor.wm;


/**
 * Java content class for anonymous complex type.
 * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/E:/wm_1_0.xsd line 127)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://www.ios.ac.cn/onceas}user-name"/>
 *           &lt;element ref="{http://www.ios.ac.cn/onceas}group-name"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.ios.ac.cn/onceas}request-class-name"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ContextCaseType {


    /**
     * Gets the value of the requestClassName property.
     * 
     * @return
     *     possible object is
     *     {@link com.onceas.descriptor.wm.TagStringValueType}
     *     {@link com.onceas.descriptor.wm.RequestClassName}
     */
    com.onceas.descriptor.wm.TagStringValueType getRequestClassName();

    /**
     * Sets the value of the requestClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.onceas.descriptor.wm.TagStringValueType}
     *     {@link com.onceas.descriptor.wm.RequestClassName}
     */
    void setRequestClassName(com.onceas.descriptor.wm.TagStringValueType value);

    /**
     * Gets the value of the groupName property.
     * 
     * @return
     *     possible object is
     *     {@link com.onceas.descriptor.wm.TagStringValueType}
     *     {@link GroupName}
     */
    com.onceas.descriptor.wm.TagStringValueType getGroupName();

    /**
     * Sets the value of the groupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.onceas.descriptor.wm.TagStringValueType}
     *     {@link GroupName}
     */
    void setGroupName(com.onceas.descriptor.wm.TagStringValueType value);

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link com.onceas.descriptor.wm.TagStringValueType}
     *     {@link UserName}
     */
    com.onceas.descriptor.wm.TagStringValueType getUserName();

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.onceas.descriptor.wm.TagStringValueType}
     *     {@link UserName}
     */
    void setUserName(com.onceas.descriptor.wm.TagStringValueType value);

}
