//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2009.11.26 дк 04:48:36 CST 
//


package com.onceas.descriptor.wm;

import javax.xml.bind.JAXBException;
import javax.xml.bind.PropertyException;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.onceas.descriptor.wm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends com.onceas.descriptor.wm.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(47, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static com.onceas.descriptor.wm.impl.runtime.GrammarInfo grammarInfo = new com.onceas.descriptor.wm.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (ObjectFactory.class));
    public final static Class version = (com.onceas.descriptor.wm.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((com.onceas.descriptor.wm.ResponseTimeRequestClass.class), "com.onceas.descriptor.wm.impl.ResponseTimeRequestClassImpl");
        defaultImplementations.put((ContextCase.class), "com.onceas.descriptor.wm.impl.ContextCaseImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.StuckThreadCount.class), "com.onceas.descriptor.wm.impl.StuckThreadCountImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.OnceasServlet.class), "com.onceas.descriptor.wm.impl.OnceasServletImpl");
        defaultImplementations.put((Wm.class), "com.onceas.descriptor.wm.impl.WmImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.WorkManagerShutdownTriggerType.class), "com.onceas.descriptor.wm.impl.WorkManagerShutdownTriggerTypeImpl");
        defaultImplementations.put((CapacityType.class), "com.onceas.descriptor.wm.impl.CapacityTypeImpl");
        defaultImplementations.put((Name.class), "com.onceas.descriptor.wm.impl.NameImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.FairShareRequestClassType.class), "com.onceas.descriptor.wm.impl.FairShareRequestClassTypeImpl");
        defaultImplementations.put((UserName.class), "com.onceas.descriptor.wm.impl.UserNameImpl");
        defaultImplementations.put((Count.class), "com.onceas.descriptor.wm.impl.CountImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.MinThreadsConstraintType.class), "com.onceas.descriptor.wm.impl.MinThreadsConstraintTypeImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.WorkManagerType.class), "com.onceas.descriptor.wm.impl.WorkManagerTypeImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.WorkManagerShutdownTrigger.class), "com.onceas.descriptor.wm.impl.WorkManagerShutdownTriggerImpl");
        defaultImplementations.put((Capacity.class), "com.onceas.descriptor.wm.impl.CapacityImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.WorkManagerBean.class), "com.onceas.descriptor.wm.impl.WorkManagerBeanImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.MinThreadsConstraint.class), "com.onceas.descriptor.wm.impl.MinThreadsConstraintImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.TagStringValueType.class), "com.onceas.descriptor.wm.impl.TagStringValueTypeImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.OnceasServletType.class), "com.onceas.descriptor.wm.impl.OnceasServletTypeImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.FairShareRequestClass.class), "com.onceas.descriptor.wm.impl.FairShareRequestClassImpl");
        defaultImplementations.put((WmType.class), "com.onceas.descriptor.wm.impl.WmTypeImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.WorkManagerBeanType.class), "com.onceas.descriptor.wm.impl.WorkManagerBeanTypeImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.MaxStuckThreadTime.class), "com.onceas.descriptor.wm.impl.MaxStuckThreadTimeImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.ContextRequestClassType.class), "com.onceas.descriptor.wm.impl.ContextRequestClassTypeImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.MaxThreadsConstraint.class), "com.onceas.descriptor.wm.impl.MaxThreadsConstraintImpl");
        defaultImplementations.put((GoalMs.class), "com.onceas.descriptor.wm.impl.GoalMsImpl");
        defaultImplementations.put((GroupName.class), "com.onceas.descriptor.wm.impl.GroupNameImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.RequestClassName.class), "com.onceas.descriptor.wm.impl.RequestClassNameImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.ContextRequestClass.class), "com.onceas.descriptor.wm.impl.ContextRequestClassImpl");
        defaultImplementations.put((FairShare.class), "com.onceas.descriptor.wm.impl.FairShareImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.ContextCaseType.class), "com.onceas.descriptor.wm.impl.ContextCaseTypeImpl");
        defaultImplementations.put((WorkManager.class), "com.onceas.descriptor.wm.impl.WorkManagerImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.MaxThreadsConstraintType.class), "com.onceas.descriptor.wm.impl.MaxThreadsConstraintTypeImpl");
        defaultImplementations.put((com.onceas.descriptor.wm.ResponseTimeRequestClassType.class), "com.onceas.descriptor.wm.impl.ResponseTimeRequestClassTypeImpl");
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "onceas-servlet"), (com.onceas.descriptor.wm.OnceasServlet.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "user-name"), (UserName.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "context-case"), (ContextCase.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "count"), (Count.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "goal-ms"), (GoalMs.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "max-threads-constraint"), (com.onceas.descriptor.wm.MaxThreadsConstraint.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "wm"), (Wm.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "response-time-request-class"), (com.onceas.descriptor.wm.ResponseTimeRequestClass.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "name"), (Name.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "request-class-name"), (com.onceas.descriptor.wm.RequestClassName.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "work-manager-bean"), (com.onceas.descriptor.wm.WorkManagerBean.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "fair-share-request-class"), (com.onceas.descriptor.wm.FairShareRequestClass.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "group-name"), (GroupName.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "work-manager"), (WorkManager.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "stuck-thread-count"), (com.onceas.descriptor.wm.StuckThreadCount.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "min-threads-constraint"), (com.onceas.descriptor.wm.MinThreadsConstraint.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "context-request-class"), (com.onceas.descriptor.wm.ContextRequestClass.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "max-stuck-thread-time"), (com.onceas.descriptor.wm.MaxStuckThreadTime.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "capacity"), (Capacity.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "work-manager-shutdown-trigger"), (com.onceas.descriptor.wm.WorkManagerShutdownTrigger.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.ios.ac.cn/onceas", "fair-share"), (FairShare.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.onceas.descriptor.wm
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public Object newInstance(Class javaContentInterface)
        throws JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public Object getProperty(String name)
        throws PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(String name, Object value)
        throws PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of ResponseTimeRequestClass
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.ResponseTimeRequestClass createResponseTimeRequestClass()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.ResponseTimeRequestClassImpl();
    }

    /**
     * Create an instance of ContextCase
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public ContextCase createContextCase()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.ContextCaseImpl();
    }

    /**
     * Create an instance of StuckThreadCount
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.StuckThreadCount createStuckThreadCount()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.StuckThreadCountImpl();
    }

    /**
     * Create an instance of OnceasServlet
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.OnceasServlet createOnceasServlet()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.OnceasServletImpl();
    }

    /**
     * Create an instance of Wm
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public Wm createWm()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.WmImpl();
    }

    /**
     * Create an instance of WorkManagerShutdownTriggerType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.WorkManagerShutdownTriggerType createWorkManagerShutdownTriggerType()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.WorkManagerShutdownTriggerTypeImpl();
    }

    /**
     * Create an instance of CapacityType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public CapacityType createCapacityType()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.CapacityTypeImpl();
    }

    /**
     * Create an instance of Name
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public Name createName()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.NameImpl();
    }

    /**
     * Create an instance of FairShareRequestClassType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.FairShareRequestClassType createFairShareRequestClassType()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.FairShareRequestClassTypeImpl();
    }

    /**
     * Create an instance of UserName
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public UserName createUserName()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.UserNameImpl();
    }

    /**
     * Create an instance of Count
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public Count createCount()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.CountImpl();
    }

    /**
     * Create an instance of MinThreadsConstraintType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.MinThreadsConstraintType createMinThreadsConstraintType()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.MinThreadsConstraintTypeImpl();
    }

    /**
     * Create an instance of WorkManagerType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.WorkManagerType createWorkManagerType()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.WorkManagerTypeImpl();
    }

    /**
     * Create an instance of WorkManagerShutdownTrigger
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.WorkManagerShutdownTrigger createWorkManagerShutdownTrigger()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.WorkManagerShutdownTriggerImpl();
    }

    /**
     * Create an instance of Capacity
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public Capacity createCapacity()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.CapacityImpl();
    }

    /**
     * Create an instance of WorkManagerBean
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.WorkManagerBean createWorkManagerBean()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.WorkManagerBeanImpl();
    }

    /**
     * Create an instance of MinThreadsConstraint
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.MinThreadsConstraint createMinThreadsConstraint()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.MinThreadsConstraintImpl();
    }

    /**
     * Create an instance of TagStringValueType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.TagStringValueType createTagStringValueType()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.TagStringValueTypeImpl();
    }

    /**
     * Create an instance of OnceasServletType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.OnceasServletType createOnceasServletType()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.OnceasServletTypeImpl();
    }

    /**
     * Create an instance of FairShareRequestClass
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.FairShareRequestClass createFairShareRequestClass()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.FairShareRequestClassImpl();
    }

    /**
     * Create an instance of WmType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public WmType createWmType()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.WmTypeImpl();
    }

    /**
     * Create an instance of WorkManagerBeanType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.WorkManagerBeanType createWorkManagerBeanType()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.WorkManagerBeanTypeImpl();
    }

    /**
     * Create an instance of MaxStuckThreadTime
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.MaxStuckThreadTime createMaxStuckThreadTime()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.MaxStuckThreadTimeImpl();
    }

    /**
     * Create an instance of ContextRequestClassType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.ContextRequestClassType createContextRequestClassType()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.ContextRequestClassTypeImpl();
    }

    /**
     * Create an instance of MaxThreadsConstraint
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.MaxThreadsConstraint createMaxThreadsConstraint()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.MaxThreadsConstraintImpl();
    }

    /**
     * Create an instance of GoalMs
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public GoalMs createGoalMs()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.GoalMsImpl();
    }

    /**
     * Create an instance of GroupName
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public GroupName createGroupName()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.GroupNameImpl();
    }

    /**
     * Create an instance of RequestClassName
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.RequestClassName createRequestClassName()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.RequestClassNameImpl();
    }

    /**
     * Create an instance of ContextRequestClass
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.ContextRequestClass createContextRequestClass()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.ContextRequestClassImpl();
    }

    /**
     * Create an instance of FairShare
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public FairShare createFairShare()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.FairShareImpl();
    }

    /**
     * Create an instance of ContextCaseType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.ContextCaseType createContextCaseType()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.ContextCaseTypeImpl();
    }

    /**
     * Create an instance of WorkManager
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public WorkManager createWorkManager()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.WorkManagerImpl();
    }

    /**
     * Create an instance of MaxThreadsConstraintType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.MaxThreadsConstraintType createMaxThreadsConstraintType()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.MaxThreadsConstraintTypeImpl();
    }

    /**
     * Create an instance of ResponseTimeRequestClassType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.onceas.descriptor.wm.ResponseTimeRequestClassType createResponseTimeRequestClassType()
        throws JAXBException
    {
        return new com.onceas.descriptor.wm.impl.ResponseTimeRequestClassTypeImpl();
    }

}
