//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2009.11.26 дк 04:48:36 CST 
//


package com.onceas.descriptor.wm;


/**
 * Java content class for stuck-thread-count element declaration.
 * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/E:/wm_1_0.xsd line 144)
 * <p>
 * <pre>
 * &lt;element name="stuck-thread-count" type="{http://www.ios.ac.cn/onceas}TagStringValueType"/>
 * </pre>
 * 
 */
public interface StuckThreadCount
    extends javax.xml.bind.Element, com.onceas.descriptor.wm.TagStringValueType
{


}
