//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2009.11.26 在 04:48:36 CST 
//


package com.onceas.descriptor.wm;


/**
 * Java content class for anonymous complex type.
 * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/E:/wm_1_0.xsd line 7)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{http://www.ios.ac.cn/onceas}onceas-servlet" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ios.ac.cn/onceas}work-manager" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface WmType {


    /**
     * Gets the value of the OnceasServlet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the OnceasServlet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOnceasServlet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.onceas.descriptor.wm.OnceasServlet}
     * {@link com.onceas.descriptor.wm.OnceasServletType}
     * 
     */
    java.util.List getOnceasServlet();

    /**
     * Gets the value of the workManager property.
     * 
     * @return
     *     possible object is
     *     {@link com.onceas.descriptor.wm.WorkManager}
     *     {@link com.onceas.descriptor.wm.WorkManagerType}
     */
    com.onceas.descriptor.wm.WorkManagerType getWorkManager();

    /**
     * Sets the value of the workManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.onceas.descriptor.wm.WorkManager}
     *     {@link com.onceas.descriptor.wm.WorkManagerType}
     */
    void setWorkManager(com.onceas.descriptor.wm.WorkManagerType value);

}
