//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2009.11.26 дк 04:48:36 CST 
//


package com.onceas.descriptor.wm;


/**
 * Java content class for work-manager-bean element declaration.
 * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/E:/wm_1_0.xsd line 32)
 * <p>
 * <pre>
 * &lt;element name="work-manager-bean">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{http://www.ios.ac.cn/onceas}name"/>
 *           &lt;choice minOccurs="0">
 *             &lt;element ref="{http://www.ios.ac.cn/onceas}fair-share-request-class" minOccurs="0"/>
 *             &lt;element ref="{http://www.ios.ac.cn/onceas}context-request-class" minOccurs="0"/>
 *             &lt;element ref="{http://www.ios.ac.cn/onceas}response-time-request-class" minOccurs="0"/>
 *           &lt;/choice>
 *           &lt;element ref="{http://www.ios.ac.cn/onceas}max-threads-constraint" minOccurs="0"/>
 *           &lt;element ref="{http://www.ios.ac.cn/onceas}min-threads-constraint" minOccurs="0"/>
 *           &lt;element ref="{http://www.ios.ac.cn/onceas}capacity" minOccurs="0"/>
 *           &lt;element ref="{http://www.ios.ac.cn/onceas}work-manager-shutdown-trigger" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface WorkManagerBean
    extends javax.xml.bind.Element, com.onceas.descriptor.wm.WorkManagerBeanType
{


}
