//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2009.11.26 дк 04:48:36 CST 
//


package com.onceas.descriptor.wm.impl;

public class WmTypeImpl implements com.onceas.descriptor.wm.WmType, com.sun.xml.bind.JAXBObject, com.onceas.descriptor.wm.impl.runtime.UnmarshallableObject, com.onceas.descriptor.wm.impl.runtime.XMLSerializable, com.onceas.descriptor.wm.impl.runtime.ValidatableObject
{

    protected com.sun.xml.bind.util.ListImpl _OnceasServlet;
    protected com.onceas.descriptor.wm.WorkManagerType _WorkManager;
    public final static Class version = (com.onceas.descriptor.wm.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static Class PRIMARY_INTERFACE_CLASS() {
        return (com.onceas.descriptor.wm.WmType.class);
    }

    protected com.sun.xml.bind.util.ListImpl _getOnceasServlet() {
        if (_OnceasServlet == null) {
            _OnceasServlet = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _OnceasServlet;
    }

    public java.util.List getOnceasServlet() {
        return _getOnceasServlet();
    }

    public com.onceas.descriptor.wm.WorkManagerType getWorkManager() {
        return _WorkManager;
    }

    public void setWorkManager(com.onceas.descriptor.wm.WorkManagerType value) {
        _WorkManager = value;
    }

    public com.onceas.descriptor.wm.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.onceas.descriptor.wm.impl.runtime.UnmarshallingContext context) {
        return new Unmarshaller(context);
    }

    public void serializeBody(com.onceas.descriptor.wm.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_OnceasServlet == null)? 0 :_OnceasServlet.size());
        while (idx1 != len1) {
            if (_OnceasServlet.get(idx1) instanceof javax.xml.bind.Element) {
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _OnceasServlet.get(idx1 ++)), "OnceasServlet");
            } else {
                context.startElement("http://www.ios.ac.cn/onceas", "onceas-servlet");
                int idx_0 = idx1;
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _OnceasServlet.get(idx_0 ++)), "OnceasServlet");
                context.endNamespaceDecls();
                int idx_1 = idx1;
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _OnceasServlet.get(idx_1 ++)), "OnceasServlet");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _OnceasServlet.get(idx1 ++)), "OnceasServlet");
                context.endElement();
            }
        }
        if (_WorkManager!= null) {
            if (_WorkManager instanceof javax.xml.bind.Element) {
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _WorkManager), "WorkManager");
            } else {
                context.startElement("http://www.ios.ac.cn/onceas", "work-manager");
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _WorkManager), "WorkManager");
                context.endNamespaceDecls();
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _WorkManager), "WorkManager");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _WorkManager), "WorkManager");
                context.endElement();
            }
        }
    }

    public void serializeAttributes(com.onceas.descriptor.wm.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_OnceasServlet == null)? 0 :_OnceasServlet.size());
        while (idx1 != len1) {
            if (_OnceasServlet.get(idx1) instanceof javax.xml.bind.Element) {
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _OnceasServlet.get(idx1 ++)), "OnceasServlet");
            } else {
                idx1 += 1;
            }
        }
        if (_WorkManager!= null) {
            if (_WorkManager instanceof javax.xml.bind.Element) {
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _WorkManager), "WorkManager");
            }
        }
    }

    public void serializeURIs(com.onceas.descriptor.wm.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_OnceasServlet == null)? 0 :_OnceasServlet.size());
        while (idx1 != len1) {
            if (_OnceasServlet.get(idx1) instanceof javax.xml.bind.Element) {
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _OnceasServlet.get(idx1 ++)), "OnceasServlet");
            } else {
                idx1 += 1;
            }
        }
        if (_WorkManager!= null) {
            if (_WorkManager instanceof javax.xml.bind.Element) {
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _WorkManager), "WorkManager");
            }
        }
    }

    public Class getPrimaryInterface() {
        return (com.onceas.descriptor.wm.WmType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000x"
+"r\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003s"
+"r\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000\u0006q\u0000~\u0000\fpsr\u0000\'c"
+"om.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClas"
+"st\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.E"
+"lementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentM"
+"odelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003q\u0000~\u0000\fp\u0000sq\u0000~\u0000\u0006ppsq\u0000~\u0000\bq\u0000~\u0000\fpsr\u0000 com.sun.msv.gr"
+"ammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\u000fxq\u0000"
+"~\u0000\u0003q\u0000~\u0000\fpsr\u00002com.sun.msv.grammar.Expression$AnyStringExpress"
+"ion\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000\u000b\u0001psr\u0000 com.sun.msv.grammar.AnyNameC"
+"lass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000x"
+"psr\u00000com.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000\u0018psr\u0000#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012Ljava/lang/String;L\u0000\fnamespaceURIq\u0000~\u0000\u001fx"
+"q\u0000~\u0000\u001at\u0000&com.onceas.descriptor.wm.OnceasServlett\u0000+http://java"
+".sun.com/jaxb/xjc/dummy-elementssq\u0000~\u0000\u000eq\u0000~\u0000\fp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u000ep"
+"p\u0000sq\u0000~\u0000\u0006ppsq\u0000~\u0000\bq\u0000~\u0000\fpsq\u0000~\u0000\u0014q\u0000~\u0000\fpq\u0000~\u0000\u0017q\u0000~\u0000\u001bq\u0000~\u0000\u001dsq\u0000~\u0000\u001et\u0000*co"
+"m.onceas.descriptor.wm.OnceasServletTypeq\u0000~\u0000\"sq\u0000~\u0000\u0006ppsq\u0000~\u0000\u0014q"
+"\u0000~\u0000\fpsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/"
+"relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/m"
+"sv/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000\"com.sun.msv.datatype.xsd.Qnam"
+"eType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicTy"
+"pe\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L"
+"\u0000\fnamespaceUriq\u0000~\u0000\u001fL\u0000\btypeNameq\u0000~\u0000\u001fL\u0000\nwhiteSpacet\u0000.Lcom/sun/"
+"msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/"
+"2001/XMLSchemat\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.WhiteSpac"
+"eProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.W"
+"hiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Expre"
+"ssion$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.ut"
+"il.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001fL\u0000\fnamespaceURIq\u0000~\u0000"
+"\u001fxpq\u0000~\u00008q\u0000~\u00007sq\u0000~\u0000\u001et\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLSchem"
+"a-instanceq\u0000~\u0000\u001dsq\u0000~\u0000\u001et\u0000\u000eonceas-servlett\u0000\u001bhttp://www.ios.ac.c"
+"n/onceasq\u0000~\u0000\u001dsq\u0000~\u0000\u0006ppsq\u0000~\u0000\u0006q\u0000~\u0000\fpsq\u0000~\u0000\u000eq\u0000~\u0000\fp\u0000sq\u0000~\u0000\u0006ppsq\u0000~\u0000\b"
+"q\u0000~\u0000\fpsq\u0000~\u0000\u0014q\u0000~\u0000\fpq\u0000~\u0000\u0017q\u0000~\u0000\u001bq\u0000~\u0000\u001dsq\u0000~\u0000\u001et\u0000$com.onceas.descrip"
+"tor.wm.WorkManagerq\u0000~\u0000\"sq\u0000~\u0000\u000eq\u0000~\u0000\fp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u000epp\u0000sq\u0000~\u0000\u0006p"
+"psq\u0000~\u0000\bq\u0000~\u0000\fpsq\u0000~\u0000\u0014q\u0000~\u0000\fpq\u0000~\u0000\u0017q\u0000~\u0000\u001bq\u0000~\u0000\u001dsq\u0000~\u0000\u001et\u0000(com.onceas."
+"descriptor.wm.WorkManagerTypeq\u0000~\u0000\"sq\u0000~\u0000\u0006ppsq\u0000~\u0000\u0014q\u0000~\u0000\fpq\u0000~\u00000q"
+"\u0000~\u0000@q\u0000~\u0000\u001dsq\u0000~\u0000\u001et\u0000\fwork-managerq\u0000~\u0000Eq\u0000~\u0000\u001dsr\u0000\"com.sun.msv.gram"
+"mar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/gram"
+"mar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.Expr"
+"essionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006p"
+"arentt\u0000$Lcom/sun/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000\u0012\u0001pq\u0000~\u0000\u0012q\u0000~"
+"\u0000&q\u0000~\u0000Iq\u0000~\u0000Qq\u0000~\u0000\u0013q\u0000~\u0000\'q\u0000~\u0000Jq\u0000~\u0000Rq\u0000~\u0000+q\u0000~\u0000Vq\u0000~\u0000Fq\u0000~\u0000\u0005q\u0000~\u0000\nq\u0000~"
+"\u0000\u0007q\u0000~\u0000\rq\u0000~\u0000Gq\u0000~\u0000$q\u0000~\u0000Ox"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.onceas.descriptor.wm.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.onceas.descriptor.wm.impl.runtime.UnmarshallingContext context) {
            super(context, "-------");
        }

        protected Unmarshaller(com.onceas.descriptor.wm.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public Object owner() {
            return WmTypeImpl.this;
        }

        public void enterElement(String ___uri, String ___local, String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  5 :
                        if (("work-manager-bean" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _WorkManager = ((com.onceas.descriptor.wm.impl.WorkManagerTypeImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.WorkManagerTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("work-manager-bean" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _WorkManager = ((com.onceas.descriptor.wm.impl.WorkManagerTypeImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.WorkManagerTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _WorkManager = ((com.onceas.descriptor.wm.impl.WorkManagerTypeImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.WorkManagerTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  3 :
                        if (("onceas-servlet" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _getOnceasServlet().add(((com.onceas.descriptor.wm.impl.OnceasServletImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.OnceasServletImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("onceas-servlet" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        if (("work-manager" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _WorkManager = ((com.onceas.descriptor.wm.impl.WorkManagerImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.WorkManagerImpl.class), 4, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("work-manager" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 5;
                            return ;
                        }
                        state = 4;
                        continue outer;
                    case  1 :
                        if (("servlet-name" == ___local)&&("" == ___uri)) {
                            _getOnceasServlet().add(((com.onceas.descriptor.wm.impl.OnceasServletTypeImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.OnceasServletTypeImpl.class), 2, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        break;
                    case  0 :
                        if (("onceas-servlet" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _getOnceasServlet().add(((com.onceas.descriptor.wm.impl.OnceasServletImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.OnceasServletImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("onceas-servlet" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        state = 3;
                        continue outer;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(String ___uri, String ___local, String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  6 :
                        if (("work-manager" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.popAttributes();
                            state = 4;
                            return ;
                        }
                        break;
                    case  5 :
                        _WorkManager = ((com.onceas.descriptor.wm.impl.WorkManagerTypeImpl) spawnChildFromLeaveElement((com.onceas.descriptor.wm.impl.WorkManagerTypeImpl.class), 6, ___uri, ___local, ___qname));
                        return ;
                    case  3 :
                        state = 4;
                        continue outer;
                    case  2 :
                        if (("onceas-servlet" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  0 :
                        state = 3;
                        continue outer;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(String ___uri, String ___local, String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  5 :
                        _WorkManager = ((com.onceas.descriptor.wm.impl.WorkManagerTypeImpl) spawnChildFromEnterAttribute((com.onceas.descriptor.wm.impl.WorkManagerTypeImpl.class), 6, ___uri, ___local, ___qname));
                        return ;
                    case  3 :
                        state = 4;
                        continue outer;
                    case  0 :
                        state = 3;
                        continue outer;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(String ___uri, String ___local, String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  5 :
                        _WorkManager = ((com.onceas.descriptor.wm.impl.WorkManagerTypeImpl) spawnChildFromLeaveAttribute((com.onceas.descriptor.wm.impl.WorkManagerTypeImpl.class), 6, ___uri, ___local, ___qname));
                        return ;
                    case  3 :
                        state = 4;
                        continue outer;
                    case  0 :
                        state = 3;
                        continue outer;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  4 :
                            revertToParentFromText(value);
                            return ;
                        case  5 :
                            _WorkManager = ((com.onceas.descriptor.wm.impl.WorkManagerTypeImpl) spawnChildFromText((com.onceas.descriptor.wm.impl.WorkManagerTypeImpl.class), 6, value));
                            return ;
                        case  3 :
                            state = 4;
                            continue outer;
                        case  0 :
                            state = 3;
                            continue outer;
                    }
                } catch (RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
