//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2009.11.26 дк 04:48:36 CST 
//


package com.onceas.descriptor.wm.impl;

public class WorkManagerBeanTypeImpl implements com.onceas.descriptor.wm.WorkManagerBeanType, com.sun.xml.bind.JAXBObject, com.onceas.descriptor.wm.impl.runtime.UnmarshallableObject, com.onceas.descriptor.wm.impl.runtime.XMLSerializable, com.onceas.descriptor.wm.impl.runtime.ValidatableObject
{

    protected com.onceas.descriptor.wm.ResponseTimeRequestClassType _ResponseTimeRequestClass;
    protected com.onceas.descriptor.wm.CapacityType _Capacity;
    protected com.onceas.descriptor.wm.ContextRequestClassType _ContextRequestClass;
    protected com.onceas.descriptor.wm.MinThreadsConstraintType _MinThreadsConstraint;
    protected com.onceas.descriptor.wm.WorkManagerShutdownTriggerType _WorkManagerShutdownTrigger;
    protected com.onceas.descriptor.wm.MaxThreadsConstraintType _MaxThreadsConstraint;
    protected com.onceas.descriptor.wm.TagStringValueType _Name;
    protected com.onceas.descriptor.wm.FairShareRequestClassType _FairShareRequestClass;
    public final static Class version = (JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static Class PRIMARY_INTERFACE_CLASS() {
        return (com.onceas.descriptor.wm.WorkManagerBeanType.class);
    }

    public com.onceas.descriptor.wm.ResponseTimeRequestClassType getResponseTimeRequestClass() {
        return _ResponseTimeRequestClass;
    }

    public void setResponseTimeRequestClass(com.onceas.descriptor.wm.ResponseTimeRequestClassType value) {
        _ResponseTimeRequestClass = value;
    }

    public com.onceas.descriptor.wm.CapacityType getCapacity() {
        return _Capacity;
    }

    public void setCapacity(com.onceas.descriptor.wm.CapacityType value) {
        _Capacity = value;
    }

    public com.onceas.descriptor.wm.ContextRequestClassType getContextRequestClass() {
        return _ContextRequestClass;
    }

    public void setContextRequestClass(com.onceas.descriptor.wm.ContextRequestClassType value) {
        _ContextRequestClass = value;
    }

    public com.onceas.descriptor.wm.MinThreadsConstraintType getMinThreadsConstraint() {
        return _MinThreadsConstraint;
    }

    public void setMinThreadsConstraint(com.onceas.descriptor.wm.MinThreadsConstraintType value) {
        _MinThreadsConstraint = value;
    }

    public com.onceas.descriptor.wm.WorkManagerShutdownTriggerType getWorkManagerShutdownTrigger() {
        return _WorkManagerShutdownTrigger;
    }

    public void setWorkManagerShutdownTrigger(com.onceas.descriptor.wm.WorkManagerShutdownTriggerType value) {
        _WorkManagerShutdownTrigger = value;
    }

    public com.onceas.descriptor.wm.MaxThreadsConstraintType getMaxThreadsConstraint() {
        return _MaxThreadsConstraint;
    }

    public void setMaxThreadsConstraint(com.onceas.descriptor.wm.MaxThreadsConstraintType value) {
        _MaxThreadsConstraint = value;
    }

    public com.onceas.descriptor.wm.TagStringValueType getName() {
        return _Name;
    }

    public void setName(com.onceas.descriptor.wm.TagStringValueType value) {
        _Name = value;
    }

    public com.onceas.descriptor.wm.FairShareRequestClassType getFairShareRequestClass() {
        return _FairShareRequestClass;
    }

    public void setFairShareRequestClass(com.onceas.descriptor.wm.FairShareRequestClassType value) {
        _FairShareRequestClass = value;
    }

    public com.onceas.descriptor.wm.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.onceas.descriptor.wm.impl.runtime.UnmarshallingContext context) {
        return new Unmarshaller(context);
    }

    public void serializeBody(com.onceas.descriptor.wm.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_Name instanceof javax.xml.bind.Element) {
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Name), "Name");
        } else {
            context.startElement("http://www.ios.ac.cn/onceas", "name");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Name), "Name");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Name), "Name");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Name), "Name");
            context.endElement();
        }
        if (((_ResponseTimeRequestClass == null)&&(_ContextRequestClass == null))&&(_FairShareRequestClass!= null)) {
            if (_FairShareRequestClass instanceof javax.xml.bind.Element) {
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _FairShareRequestClass), "FairShareRequestClass");
            } else {
                context.startElement("http://www.ios.ac.cn/onceas", "fair-share-request-class");
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _FairShareRequestClass), "FairShareRequestClass");
                context.endNamespaceDecls();
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _FairShareRequestClass), "FairShareRequestClass");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _FairShareRequestClass), "FairShareRequestClass");
                context.endElement();
            }
        } else {
            if (((_ResponseTimeRequestClass == null)&&(_ContextRequestClass!= null))&&(_FairShareRequestClass == null)) {
                if (_ContextRequestClass instanceof javax.xml.bind.Element) {
                    context.childAsBody(((com.sun.xml.bind.JAXBObject) _ContextRequestClass), "ContextRequestClass");
                } else {
                    context.startElement("http://www.ios.ac.cn/onceas", "context-request-class");
                    context.childAsURIs(((com.sun.xml.bind.JAXBObject) _ContextRequestClass), "ContextRequestClass");
                    context.endNamespaceDecls();
                    context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _ContextRequestClass), "ContextRequestClass");
                    context.endAttributes();
                    context.childAsBody(((com.sun.xml.bind.JAXBObject) _ContextRequestClass), "ContextRequestClass");
                    context.endElement();
                }
            } else {
                if (((_ResponseTimeRequestClass!= null)&&(_ContextRequestClass == null))&&(_FairShareRequestClass == null)) {
                    if (_ResponseTimeRequestClass instanceof javax.xml.bind.Element) {
                        context.childAsBody(((com.sun.xml.bind.JAXBObject) _ResponseTimeRequestClass), "ResponseTimeRequestClass");
                    } else {
                        context.startElement("http://www.ios.ac.cn/onceas", "response-time-request-class");
                        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _ResponseTimeRequestClass), "ResponseTimeRequestClass");
                        context.endNamespaceDecls();
                        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _ResponseTimeRequestClass), "ResponseTimeRequestClass");
                        context.endAttributes();
                        context.childAsBody(((com.sun.xml.bind.JAXBObject) _ResponseTimeRequestClass), "ResponseTimeRequestClass");
                        context.endElement();
                    }
                }
            }
        }
        if (_MaxThreadsConstraint!= null) {
            if (_MaxThreadsConstraint instanceof javax.xml.bind.Element) {
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _MaxThreadsConstraint), "MaxThreadsConstraint");
            } else {
                context.startElement("http://www.ios.ac.cn/onceas", "max-threads-constraint");
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _MaxThreadsConstraint), "MaxThreadsConstraint");
                context.endNamespaceDecls();
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _MaxThreadsConstraint), "MaxThreadsConstraint");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _MaxThreadsConstraint), "MaxThreadsConstraint");
                context.endElement();
            }
        }
        if (_MinThreadsConstraint!= null) {
            if (_MinThreadsConstraint instanceof javax.xml.bind.Element) {
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _MinThreadsConstraint), "MinThreadsConstraint");
            } else {
                context.startElement("http://www.ios.ac.cn/onceas", "min-threads-constraint");
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _MinThreadsConstraint), "MinThreadsConstraint");
                context.endNamespaceDecls();
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _MinThreadsConstraint), "MinThreadsConstraint");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _MinThreadsConstraint), "MinThreadsConstraint");
                context.endElement();
            }
        }
        if (_Capacity!= null) {
            if (_Capacity instanceof javax.xml.bind.Element) {
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _Capacity), "Capacity");
            } else {
                context.startElement("http://www.ios.ac.cn/onceas", "capacity");
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Capacity), "Capacity");
                context.endNamespaceDecls();
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Capacity), "Capacity");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _Capacity), "Capacity");
                context.endElement();
            }
        }
        if (_WorkManagerShutdownTrigger!= null) {
            if (_WorkManagerShutdownTrigger instanceof javax.xml.bind.Element) {
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _WorkManagerShutdownTrigger), "WorkManagerShutdownTrigger");
            } else {
                context.startElement("http://www.ios.ac.cn/onceas", "work-manager-shutdown-trigger");
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _WorkManagerShutdownTrigger), "WorkManagerShutdownTrigger");
                context.endNamespaceDecls();
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _WorkManagerShutdownTrigger), "WorkManagerShutdownTrigger");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _WorkManagerShutdownTrigger), "WorkManagerShutdownTrigger");
                context.endElement();
            }
        }
    }

    public void serializeAttributes(com.onceas.descriptor.wm.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_Name instanceof javax.xml.bind.Element) {
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Name), "Name");
        }
        if (((_ResponseTimeRequestClass == null)&&(_ContextRequestClass == null))&&(_FairShareRequestClass!= null)) {
            if (_FairShareRequestClass instanceof javax.xml.bind.Element) {
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _FairShareRequestClass), "FairShareRequestClass");
            }
        } else {
            if (((_ResponseTimeRequestClass == null)&&(_ContextRequestClass!= null))&&(_FairShareRequestClass == null)) {
                if (_ContextRequestClass instanceof javax.xml.bind.Element) {
                    context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _ContextRequestClass), "ContextRequestClass");
                }
            } else {
                if (((_ResponseTimeRequestClass!= null)&&(_ContextRequestClass == null))&&(_FairShareRequestClass == null)) {
                    if (_ResponseTimeRequestClass instanceof javax.xml.bind.Element) {
                        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _ResponseTimeRequestClass), "ResponseTimeRequestClass");
                    }
                }
            }
        }
        if (_MaxThreadsConstraint!= null) {
            if (_MaxThreadsConstraint instanceof javax.xml.bind.Element) {
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _MaxThreadsConstraint), "MaxThreadsConstraint");
            }
        }
        if (_MinThreadsConstraint!= null) {
            if (_MinThreadsConstraint instanceof javax.xml.bind.Element) {
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _MinThreadsConstraint), "MinThreadsConstraint");
            }
        }
        if (_Capacity!= null) {
            if (_Capacity instanceof javax.xml.bind.Element) {
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Capacity), "Capacity");
            }
        }
        if (_WorkManagerShutdownTrigger!= null) {
            if (_WorkManagerShutdownTrigger instanceof javax.xml.bind.Element) {
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _WorkManagerShutdownTrigger), "WorkManagerShutdownTrigger");
            }
        }
    }

    public void serializeURIs(com.onceas.descriptor.wm.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_Name instanceof javax.xml.bind.Element) {
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Name), "Name");
        }
        if (((_ResponseTimeRequestClass == null)&&(_ContextRequestClass == null))&&(_FairShareRequestClass!= null)) {
            if (_FairShareRequestClass instanceof javax.xml.bind.Element) {
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _FairShareRequestClass), "FairShareRequestClass");
            }
        } else {
            if (((_ResponseTimeRequestClass == null)&&(_ContextRequestClass!= null))&&(_FairShareRequestClass == null)) {
                if (_ContextRequestClass instanceof javax.xml.bind.Element) {
                    context.childAsURIs(((com.sun.xml.bind.JAXBObject) _ContextRequestClass), "ContextRequestClass");
                }
            } else {
                if (((_ResponseTimeRequestClass!= null)&&(_ContextRequestClass == null))&&(_FairShareRequestClass == null)) {
                    if (_ResponseTimeRequestClass instanceof javax.xml.bind.Element) {
                        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _ResponseTimeRequestClass), "ResponseTimeRequestClass");
                    }
                }
            }
        }
        if (_MaxThreadsConstraint!= null) {
            if (_MaxThreadsConstraint instanceof javax.xml.bind.Element) {
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _MaxThreadsConstraint), "MaxThreadsConstraint");
            }
        }
        if (_MinThreadsConstraint!= null) {
            if (_MinThreadsConstraint instanceof javax.xml.bind.Element) {
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _MinThreadsConstraint), "MinThreadsConstraint");
            }
        }
        if (_Capacity!= null) {
            if (_Capacity instanceof javax.xml.bind.Element) {
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Capacity), "Capacity");
            }
        }
        if (_WorkManagerShutdownTrigger!= null) {
            if (_WorkManagerShutdownTrigger instanceof javax.xml.bind.Element) {
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _WorkManagerShutdownTrigger), "WorkManagerShutdownTrigger");
            }
        }
    }

    public Class getPrimaryInterface() {
        return (com.onceas.descriptor.wm.WorkManagerBeanType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\u001dcom."
+"sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000\'com.sun.msv."
+"grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/su"
+"n/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq"
+"\u0000~\u0000\u0003pp\u0000sq\u0000~\u0000\nppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~"
+"\u0000\u0003sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000 com.sun.ms"
+"v.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000"
+"\rxq\u0000~\u0000\u0003q\u0000~\u0000\u0015psr\u00002com.sun.msv.grammar.Expression$AnyStringExp"
+"ression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000\u0014\u0001psr\u0000 com.sun.msv.grammar.AnyN"
+"ameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000\u001apsr\u0000#com.sun.msv.grammar.SimpleNameClass\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012Ljava/lang/String;L\u0000\fnamespaceURIq\u0000"
+"~\u0000!xq\u0000~\u0000\u001ct\u0000\u001dcom.onceas.descriptor.wm.Namet\u0000+http://java.sun."
+"com/jaxb/xjc/dummy-elementssq\u0000~\u0000\fpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\fpp\u0000sq\u0000~\u0000\np"
+"psq\u0000~\u0000\u0011q\u0000~\u0000\u0015psq\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u0000\u0019q\u0000~\u0000\u001dq\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000+com.onceas."
+"descriptor.wm.TagStringValueTypeq\u0000~\u0000$sq\u0000~\u0000\nppsq\u0000~\u0000\u0016q\u0000~\u0000\u0015psr\u0000"
+"\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/"
+"datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/"
+"StringPair;xq\u0000~\u0000\u0003ppsr\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000"
+"\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamesp"
+"aceUriq\u0000~\u0000!L\u0000\btypeNameq\u0000~\u0000!L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/data"
+"type/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XML"
+"Schemat\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcess"
+"or$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpac"
+"eProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Expression$Nu"
+"llSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.util.Strin"
+"gPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000!L\u0000\fnamespaceURIq\u0000~\u0000!xpq\u0000~\u0000:"
+"q\u0000~\u00009sq\u0000~\u0000 t\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLSchema-instan"
+"ceq\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000\u0004namet\u0000\u001bhttp://www.ios.ac.cn/onceassq\u0000~\u0000\nppsq"
+"\u0000~\u0000\nppsq\u0000~\u0000\nppsq\u0000~\u0000\nppsq\u0000~\u0000\nppsq\u0000~\u0000\nq\u0000~\u0000\u0015psq\u0000~\u0000\fq\u0000~\u0000\u0015p\u0000sq\u0000~\u0000"
+"\nppsq\u0000~\u0000\u0011q\u0000~\u0000\u0015psq\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u0000\u0019q\u0000~\u0000\u001dq\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000.com.oncea"
+"s.descriptor.wm.FairShareRequestClassq\u0000~\u0000$sq\u0000~\u0000\fq\u0000~\u0000\u0015p\u0000sq\u0000~\u0000"
+"\u0000ppsq\u0000~\u0000\fpp\u0000sq\u0000~\u0000\nppsq\u0000~\u0000\u0011q\u0000~\u0000\u0015psq\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u0000\u0019q\u0000~\u0000\u001dq\u0000~\u0000\u001fs"
+"q\u0000~\u0000 t\u00002com.onceas.descriptor.wm.FairShareRequestClassTypeq\u0000"
+"~\u0000$sq\u0000~\u0000\nppsq\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u00002q\u0000~\u0000Bq\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000\u0018fair-share-re"
+"quest-classq\u0000~\u0000Gq\u0000~\u0000\u001fsq\u0000~\u0000\fpp\u0000sq\u0000~\u0000\nppsq\u0000~\u0000\u0011q\u0000~\u0000\u0015psq\u0000~\u0000\u0016q\u0000~\u0000"
+"\u0015pq\u0000~\u0000\u0019q\u0000~\u0000\u001dq\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000,com.onceas.descriptor.wm.ContextRe"
+"questClassq\u0000~\u0000$sq\u0000~\u0000\fpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\fpp\u0000sq\u0000~\u0000\nppsq\u0000~\u0000\u0011q\u0000~\u0000\u0015"
+"psq\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u0000\u0019q\u0000~\u0000\u001dq\u0000~\u0000\u001fsq\u0000~\u0000 t\u00000com.onceas.descriptor.w"
+"m.ContextRequestClassTypeq\u0000~\u0000$sq\u0000~\u0000\nppsq\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u00002q\u0000~\u0000B"
+"q\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000\u0015context-request-classq\u0000~\u0000Gsq\u0000~\u0000\fpp\u0000sq\u0000~\u0000\nppsq\u0000"
+"~\u0000\u0011q\u0000~\u0000\u0015psq\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u0000\u0019q\u0000~\u0000\u001dq\u0000~\u0000\u001fsq\u0000~\u0000 t\u00001com.onceas.desc"
+"riptor.wm.ResponseTimeRequestClassq\u0000~\u0000$sq\u0000~\u0000\fpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~"
+"\u0000\fpp\u0000sq\u0000~\u0000\nppsq\u0000~\u0000\u0011q\u0000~\u0000\u0015psq\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u0000\u0019q\u0000~\u0000\u001dq\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000"
+"5com.onceas.descriptor.wm.ResponseTimeRequestClassTypeq\u0000~\u0000$s"
+"q\u0000~\u0000\nppsq\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u00002q\u0000~\u0000Bq\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000\u001bresponse-time-req"
+"uest-classq\u0000~\u0000Gsq\u0000~\u0000\nppsq\u0000~\u0000\nq\u0000~\u0000\u0015psq\u0000~\u0000\fq\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\nppsq\u0000~"
+"\u0000\u0011q\u0000~\u0000\u0015psq\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u0000\u0019q\u0000~\u0000\u001dq\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000-com.onceas.descr"
+"iptor.wm.MaxThreadsConstraintq\u0000~\u0000$sq\u0000~\u0000\fq\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000"
+"\fpp\u0000sq\u0000~\u0000\nppsq\u0000~\u0000\u0011q\u0000~\u0000\u0015psq\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u0000\u0019q\u0000~\u0000\u001dq\u0000~\u0000\u001fsq\u0000~\u0000 t\u00001"
+"com.onceas.descriptor.wm.MaxThreadsConstraintTypeq\u0000~\u0000$sq\u0000~\u0000\n"
+"ppsq\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u00002q\u0000~\u0000Bq\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000\u0016max-threads-constraint"
+"q\u0000~\u0000Gq\u0000~\u0000\u001fsq\u0000~\u0000\nppsq\u0000~\u0000\nq\u0000~\u0000\u0015psq\u0000~\u0000\fq\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\nppsq\u0000~\u0000\u0011q\u0000~"
+"\u0000\u0015psq\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u0000\u0019q\u0000~\u0000\u001dq\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000-com.onceas.descriptor"
+".wm.MinThreadsConstraintq\u0000~\u0000$sq\u0000~\u0000\fq\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\fpp\u0000s"
+"q\u0000~\u0000\nppsq\u0000~\u0000\u0011q\u0000~\u0000\u0015psq\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u0000\u0019q\u0000~\u0000\u001dq\u0000~\u0000\u001fsq\u0000~\u0000 t\u00001com.o"
+"nceas.descriptor.wm.MinThreadsConstraintTypeq\u0000~\u0000$sq\u0000~\u0000\nppsq\u0000"
+"~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u00002q\u0000~\u0000Bq\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000\u0016min-threads-constraintq\u0000~\u0000G"
+"q\u0000~\u0000\u001fsq\u0000~\u0000\nppsq\u0000~\u0000\nq\u0000~\u0000\u0015psq\u0000~\u0000\fq\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\nppsq\u0000~\u0000\u0011q\u0000~\u0000\u0015psq"
+"\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u0000\u0019q\u0000~\u0000\u001dq\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000!com.onceas.descriptor.wm.C"
+"apacityq\u0000~\u0000$sq\u0000~\u0000\fq\u0000~\u0000\u0015p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\fpp\u0000sq\u0000~\u0000\nppsq\u0000~\u0000\u0011q\u0000~\u0000"
+"\u0015psq\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u0000\u0019q\u0000~\u0000\u001dq\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000%com.onceas.descriptor."
+"wm.CapacityTypeq\u0000~\u0000$sq\u0000~\u0000\nppsq\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u00002q\u0000~\u0000Bq\u0000~\u0000\u001fsq\u0000~\u0000"
+" t\u0000\bcapacityq\u0000~\u0000Gq\u0000~\u0000\u001fsq\u0000~\u0000\nppsq\u0000~\u0000\nq\u0000~\u0000\u0015psq\u0000~\u0000\fq\u0000~\u0000\u0015p\u0000sq\u0000~\u0000"
+"\nppsq\u0000~\u0000\u0011q\u0000~\u0000\u0015psq\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u0000\u0019q\u0000~\u0000\u001dq\u0000~\u0000\u001fsq\u0000~\u0000 t\u00003com.oncea"
+"s.descriptor.wm.WorkManagerShutdownTriggerq\u0000~\u0000$sq\u0000~\u0000\fq\u0000~\u0000\u0015p\u0000"
+"sq\u0000~\u0000\u0000ppsq\u0000~\u0000\fpp\u0000sq\u0000~\u0000\nppsq\u0000~\u0000\u0011q\u0000~\u0000\u0015psq\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u0000\u0019q\u0000~\u0000\u001dq"
+"\u0000~\u0000\u001fsq\u0000~\u0000 t\u00007com.onceas.descriptor.wm.WorkManagerShutdownTri"
+"ggerTypeq\u0000~\u0000$sq\u0000~\u0000\nppsq\u0000~\u0000\u0016q\u0000~\u0000\u0015pq\u0000~\u00002q\u0000~\u0000Bq\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000\u001dwor"
+"k-manager-shutdown-triggerq\u0000~\u0000Gq\u0000~\u0000\u001fsr\u0000\"com.sun.msv.grammar."
+"ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/"
+"ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.Expressi"
+"onPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006paren"
+"tt\u0000$Lcom/sun/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000D\u0001pq\u0000~\u0000\u00b5q\u0000~\u0000\u00a1q\u0000"
+"~\u0000\u008dq\u0000~\u0000yq\u0000~\u0000gq\u0000~\u0000Uq\u0000~\u0000&q\u0000~\u0000\u00c9q\u0000~\u0000\u0005q\u0000~\u0000Hq\u0000~\u0000Kq\u0000~\u0000Iq\u0000~\u0000\bq\u0000~\u0000\u00bcq\u0000"
+"~\u0000\u00a8q\u0000~\u0000\u0094q\u0000~\u0000\u0080q\u0000~\u0000nq\u0000~\u0000\\q\u0000~\u0000-q\u0000~\u0000\u0006q\u0000~\u0000\u00d0q\u0000~\u0000\u00adq\u0000~\u0000\u0099q\u0000~\u0000\u0085q\u0000~\u0000Mq\u0000"
+"~\u0000\u000bq\u0000~\u0000\u0098q\u0000~\u0000\u0084q\u0000~\u0000Lq\u0000~\u0000\u00acq\u0000~\u0000\u00c1q\u0000~\u0000\u00c0q\u0000~\u0000\tq\u0000~\u0000\u00b8q\u0000~\u0000\u00b0q\u0000~\u0000\u00a4q\u0000~\u0000\u009cq\u0000"
+"~\u0000\u0090q\u0000~\u0000\u0088q\u0000~\u0000|q\u0000~\u0000tq\u0000~\u0000jq\u0000~\u0000bq\u0000~\u0000Xq\u0000~\u0000Pq\u0000~\u0000)q\u0000~\u0000\u0013q\u0000~\u0000\u00c4q\u0000~\u0000\u00ccq\u0000"
+"~\u0000\u00b7q\u0000~\u0000\u00afq\u0000~\u0000\u00a3q\u0000~\u0000\u009bq\u0000~\u0000\u008fq\u0000~\u0000\u0087q\u0000~\u0000{q\u0000~\u0000sq\u0000~\u0000iq\u0000~\u0000aq\u0000~\u0000Wq\u0000~\u0000Oq\u0000"
+"~\u0000(q\u0000~\u0000\u0010q\u0000~\u0000\u0007q\u0000~\u0000Jq\u0000~\u0000\u00c3q\u0000~\u0000\u00cbx"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.onceas.descriptor.wm.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.onceas.descriptor.wm.impl.runtime.UnmarshallingContext context) {
            super(context, "-----------------------");
        }

        protected Unmarshaller(com.onceas.descriptor.wm.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public Object owner() {
            return WorkManagerBeanTypeImpl.this;
        }

        public void enterElement(String ___uri, String ___local, String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  15 :
                        if (("name" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _Capacity = ((CapacityTypeImpl) spawnChildFromEnterElement((CapacityTypeImpl.class), 16, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("name" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _Capacity = ((CapacityTypeImpl) spawnChildFromEnterElement((CapacityTypeImpl.class), 16, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  4 :
                        if (("max-threads-constraint" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _MaxThreadsConstraint = ((com.onceas.descriptor.wm.impl.MaxThreadsConstraintImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.MaxThreadsConstraintImpl.class), 7, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("max-threads-constraint" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 5;
                            return ;
                        }
                        state = 7;
                        continue outer;
                    case  13 :
                        if (("max-stuck-thread-time" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _WorkManagerShutdownTrigger = ((com.onceas.descriptor.wm.impl.WorkManagerShutdownTriggerTypeImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.WorkManagerShutdownTriggerTypeImpl.class), 14, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("max-stuck-thread-time" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _WorkManagerShutdownTrigger = ((com.onceas.descriptor.wm.impl.WorkManagerShutdownTriggerTypeImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.WorkManagerShutdownTriggerTypeImpl.class), 14, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  7 :
                        if (("min-threads-constraint" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _MinThreadsConstraint = ((com.onceas.descriptor.wm.impl.MinThreadsConstraintImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.MinThreadsConstraintImpl.class), 10, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("min-threads-constraint" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 8;
                            return ;
                        }
                        state = 10;
                        continue outer;
                    case  12 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  10 :
                        if (("capacity" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _Capacity = ((CapacityImpl) spawnChildFromEnterElement((CapacityImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("capacity" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 15;
                            return ;
                        }
                        state = 11;
                        continue outer;
                    case  8 :
                        if (("name" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _MinThreadsConstraint = ((com.onceas.descriptor.wm.impl.MinThreadsConstraintTypeImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.MinThreadsConstraintTypeImpl.class), 9, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("name" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _MinThreadsConstraint = ((com.onceas.descriptor.wm.impl.MinThreadsConstraintTypeImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.MinThreadsConstraintTypeImpl.class), 9, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  19 :
                        if (("name" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _ContextRequestClass = ((com.onceas.descriptor.wm.impl.ContextRequestClassTypeImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.ContextRequestClassTypeImpl.class), 20, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("name" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _ContextRequestClass = ((com.onceas.descriptor.wm.impl.ContextRequestClassTypeImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.ContextRequestClassTypeImpl.class), 20, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  1 :
                        if (("fair-share-request-class" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _FairShareRequestClass = ((com.onceas.descriptor.wm.impl.FairShareRequestClassImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.FairShareRequestClassImpl.class), 4, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("fair-share-request-class" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 17;
                            return ;
                        }
                        if (("context-request-class" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _ContextRequestClass = ((ContextRequestClassImpl) spawnChildFromEnterElement((ContextRequestClassImpl.class), 4, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("context-request-class" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 19;
                            return ;
                        }
                        if (("response-time-request-class" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _ResponseTimeRequestClass = ((com.onceas.descriptor.wm.impl.ResponseTimeRequestClassImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.ResponseTimeRequestClassImpl.class), 4, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("response-time-request-class" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 2;
                            return ;
                        }
                        state = 4;
                        continue outer;
                    case  0 :
                        if (("name" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _Name = ((NameImpl) spawnChildFromEnterElement((NameImpl.class), 1, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("name" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 21;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("name" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _ResponseTimeRequestClass = ((com.onceas.descriptor.wm.impl.ResponseTimeRequestClassTypeImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.ResponseTimeRequestClassTypeImpl.class), 3, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("name" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _ResponseTimeRequestClass = ((com.onceas.descriptor.wm.impl.ResponseTimeRequestClassTypeImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.ResponseTimeRequestClassTypeImpl.class), 3, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  5 :
                        if (("name" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _MaxThreadsConstraint = ((com.onceas.descriptor.wm.impl.MaxThreadsConstraintTypeImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.MaxThreadsConstraintTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("name" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _MaxThreadsConstraint = ((com.onceas.descriptor.wm.impl.MaxThreadsConstraintTypeImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.MaxThreadsConstraintTypeImpl.class), 6, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  11 :
                        if (("work-manager-shutdown-trigger" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _WorkManagerShutdownTrigger = ((com.onceas.descriptor.wm.impl.WorkManagerShutdownTriggerImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.WorkManagerShutdownTriggerImpl.class), 12, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("work-manager-shutdown-trigger" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 13;
                            return ;
                        }
                        state = 12;
                        continue outer;
                    case  17 :
                        if (("name" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _FairShareRequestClass = ((com.onceas.descriptor.wm.impl.FairShareRequestClassTypeImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.FairShareRequestClassTypeImpl.class), 18, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("name" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            _FairShareRequestClass = ((com.onceas.descriptor.wm.impl.FairShareRequestClassTypeImpl) spawnChildFromEnterElement((com.onceas.descriptor.wm.impl.FairShareRequestClassTypeImpl.class), 18, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(String ___uri, String ___local, String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        state = 7;
                        continue outer;
                    case  7 :
                        state = 10;
                        continue outer;
                    case  9 :
                        if (("min-threads-constraint" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.popAttributes();
                            state = 10;
                            return ;
                        }
                        break;
                    case  12 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  10 :
                        state = 11;
                        continue outer;
                    case  20 :
                        if (("context-request-class" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.popAttributes();
                            state = 4;
                            return ;
                        }
                        break;
                    case  3 :
                        if (("response-time-request-class" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.popAttributes();
                            state = 4;
                            return ;
                        }
                        break;
                    case  18 :
                        if (("fair-share-request-class" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.popAttributes();
                            state = 4;
                            return ;
                        }
                        break;
                    case  1 :
                        state = 4;
                        continue outer;
                    case  14 :
                        if (("work-manager-shutdown-trigger" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.popAttributes();
                            state = 12;
                            return ;
                        }
                        break;
                    case  11 :
                        state = 12;
                        continue outer;
                    case  6 :
                        if (("max-threads-constraint" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.popAttributes();
                            state = 7;
                            return ;
                        }
                        break;
                    case  22 :
                        if (("name" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.popAttributes();
                            state = 1;
                            return ;
                        }
                        break;
                    case  16 :
                        if (("capacity" == ___local)&&("http://www.ios.ac.cn/onceas" == ___uri)) {
                            context.popAttributes();
                            state = 11;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(String ___uri, String ___local, String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        state = 7;
                        continue outer;
                    case  7 :
                        state = 10;
                        continue outer;
                    case  12 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  10 :
                        state = 11;
                        continue outer;
                    case  1 :
                        state = 4;
                        continue outer;
                    case  11 :
                        state = 12;
                        continue outer;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(String ___uri, String ___local, String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        state = 7;
                        continue outer;
                    case  7 :
                        state = 10;
                        continue outer;
                    case  12 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  10 :
                        state = 11;
                        continue outer;
                    case  1 :
                        state = 4;
                        continue outer;
                    case  11 :
                        state = 12;
                        continue outer;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  4 :
                            state = 7;
                            continue outer;
                        case  7 :
                            state = 10;
                            continue outer;
                        case  12 :
                            revertToParentFromText(value);
                            return ;
                        case  10 :
                            state = 11;
                            continue outer;
                        case  1 :
                            state = 4;
                            continue outer;
                        case  21 :
                            _Name = ((TagStringValueTypeImpl) spawnChildFromText((TagStringValueTypeImpl.class), 22, value));
                            return ;
                        case  11 :
                            state = 12;
                            continue outer;
                    }
                } catch (RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
